import { useEffect, useState } from "react";
import secretFriendImage from "/secret_friend2.png";

export function WelcomePage() {
  //stores an array with all friends
  const [arrayFriends, setArrysFriends] = useState([]);

  //stores a string with the friend's name
  const [inputFriend, setInputFriend] = useState("");

  //keep the winner
  const [winner, setWinner] = useState("");

  //distance from the center to the edge of the circle
  const radius = 250; //circle radius

  //handle any changes in the input
  const handleChange = (e) => {
    setInputFriend(e.target.value);
  };

  // useEffect(()=>{
  //   console.log(inputFriend)
  // },[inputFriend])

  //add the content of friends to the array
  const handlePush = (e) => {
    //remove spaces and check if it is different from an empty string
    if (inputFriend.trim() !== "") {
      //conditional if the friend is already in the array
      if (!arrayFriends.includes(inputFriend.trim())) {
        //give the array our new friend
        setArrysFriends((prev) => [...prev, inputFriend.trim()]);
      } else {
        //if it is already in the array for the flow and gives an alert
        return alert("Este amigo ya existe porfavor inserte uno nuevo");
      }
      //clean the input
      setInputFriend("");
    } else {
      //If the input content is an empty string, it gives a warning and stops the flow.
      return alert("Porfavor inserte un nombre antes de continuar");
    }
  };

  //empties both the input and the array of friends
  const handleEmpty = (e) => {
    setInputFriend("");
    setArrysFriends([]);
  };

  //Draw a random number from all your friends and use that to determine a winner.
  const handleSort = (e) => {
    //gives a ramdom number
    const numFriendsWinner = Math.floor(Math.random() * arrayFriends.length);

    //set winner this ramdon number
    setWinner(arrayFriends[numFriendsWinner]);
  };

  return (
    <div className="w-full h-auto flex justify-center items-center">
      <div className="relative w-[300px] h-screen rounded-full flex items-center justify-center">
        <div className="w-auto absolute flex flex-col items-center gap-2">
          {/* image generated by IA */}
          <img className="w-40 h-40" src={secretFriendImage} alt="" />
          {/* just a title */}
          <h1 className="text-3xl font-semibold text-yellow-500 drop-shadow-lg tracking-wide text-center">
            Escribe el nombre de un amigo
          </h1>
          {/* inputfriends, where you type the name */}
          <input
            type="text"
            className="w-60 px-2 py-1 rounded-md border border-gray-400"
            placeholder="Escribe un nombre"
            onChange={handleChange}
            value={inputFriend}
          />
          <div className="w-60 flex flex-row place-content-between">
            <button
              className="bg-[#33312B] text-white px-4 py-1 rounded-md transition-transform duration-300 ease-in-out  hover:bg-[#756A3B] hover:scale-125"
              // call the handlePush function
              onClick={handlePush}
            >
              Agregar
            </button>
            <button
              className="bg-[#33312B] text-white px-4 py-1 rounded-md transition-transform duration-300 ease-in-out  hover:bg-[#756A3B] hover:scale-125"
              // call the handleEmpty function
              onClick={handleEmpty}
            >
              Vaciar
            </button>
          </div>
          {/* the size of the array is greater than zero (conditional render)*/}
          {arrayFriends.length > 0 && (
            <button
              className="bg-[#33312B] text-white px-4 py-1 rounded-md transition-transform duration-300 ease-in-out  hover:bg-[#756A3B] hover:scale-125 z-40"
              //call the handleSort function
              onClick={handleSort}
            >
              Sortear
            </button>
          )}
        </div>

        {/* The arrayFriends exists, and if so, perform a .map (go through item by item). */}
        {arrayFriends?.map((friend, index) => {
          //give a angle
          const angle = (index / arrayFriends.length) * 2 * Math.PI;
          //gives a x position
          const x = radius * Math.cos(angle);
          //gives a y position
          const y = radius * Math.sin(angle);
          return (
            <div
              key={index}
              className="w-20 h-20 rounded-full bg-[#F4C200] text-white flex items-center justify-center absolute transition-transform duration-700 ease-out hover:scale-105"
              //define your exact position
              style={{
                transform: `translate(${x}px, ${y}px)`,
              }}
            >
              <h1 className="text-sm text-center leading-none">{friend}</h1>
            </div>
          );
        })}

        {winner && (
          <div
            className="fixed inset-0 bg-[rgba(0,0,0,0.5)] flex items-center justify-center z-50"
            onClick={()=>setWinner("")}
          >
            <div className="bg-white p-6 rounded-lg shadow-lg w-96">
              <h1 className="text-4xl font-semibold text-[#33312B] drop-shadow-lg tracking-wide text-center">
                El ganador es
                <p className="text-4xl font-semibold text-yellow-500 drop-shadow-lg tracking-wide text-center">
                  {winner}
                </p>
              </h1>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
